require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DxesController do

  # This should return the minimal set of attributes required to create a valid
  # Dx. As you add validations to Dx, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DxesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all dxes as @dxes" do
      dx = Dx.create! valid_attributes
      get :index, {}, valid_session
      assigns(:dxes).should eq([dx])
    end
  end

  describe "GET show" do
    it "assigns the requested dx as @dx" do
      dx = Dx.create! valid_attributes
      get :show, {:id => dx.to_param}, valid_session
      assigns(:dx).should eq(dx)
    end
  end

  describe "GET new" do
    it "assigns a new dx as @dx" do
      get :new, {}, valid_session
      assigns(:dx).should be_a_new(Dx)
    end
  end

  describe "GET edit" do
    it "assigns the requested dx as @dx" do
      dx = Dx.create! valid_attributes
      get :edit, {:id => dx.to_param}, valid_session
      assigns(:dx).should eq(dx)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Dx" do
        expect {
          post :create, {:dx => valid_attributes}, valid_session
        }.to change(Dx, :count).by(1)
      end

      it "assigns a newly created dx as @dx" do
        post :create, {:dx => valid_attributes}, valid_session
        assigns(:dx).should be_a(Dx)
        assigns(:dx).should be_persisted
      end

      it "redirects to the created dx" do
        post :create, {:dx => valid_attributes}, valid_session
        response.should redirect_to(Dx.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dx as @dx" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dx.any_instance.stub(:save).and_return(false)
        post :create, {:dx => { "name" => "invalid value" }}, valid_session
        assigns(:dx).should be_a_new(Dx)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Dx.any_instance.stub(:save).and_return(false)
        post :create, {:dx => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dx" do
        dx = Dx.create! valid_attributes
        # Assuming there are no other dxes in the database, this
        # specifies that the Dx created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Dx.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => dx.to_param, :dx => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested dx as @dx" do
        dx = Dx.create! valid_attributes
        put :update, {:id => dx.to_param, :dx => valid_attributes}, valid_session
        assigns(:dx).should eq(dx)
      end

      it "redirects to the dx" do
        dx = Dx.create! valid_attributes
        put :update, {:id => dx.to_param, :dx => valid_attributes}, valid_session
        response.should redirect_to(dx)
      end
    end

    describe "with invalid params" do
      it "assigns the dx as @dx" do
        dx = Dx.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dx.any_instance.stub(:save).and_return(false)
        put :update, {:id => dx.to_param, :dx => { "name" => "invalid value" }}, valid_session
        assigns(:dx).should eq(dx)
      end

      it "re-renders the 'edit' template" do
        dx = Dx.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Dx.any_instance.stub(:save).and_return(false)
        put :update, {:id => dx.to_param, :dx => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dx" do
      dx = Dx.create! valid_attributes
      expect {
        delete :destroy, {:id => dx.to_param}, valid_session
      }.to change(Dx, :count).by(-1)
    end

    it "redirects to the dxes list" do
      dx = Dx.create! valid_attributes
      delete :destroy, {:id => dx.to_param}, valid_session
      response.should redirect_to(dxes_url)
    end
  end

end
